---
- name: Create template file from base64
  template:
    src: chrony.conf.j2 
    dest: "{{ config_dest }}/chrony.conf"
- name: Set chrony.conf in base64 format
  slurp: 
      src: "{{ config_dest }}/chrony.conf"
  register: chrony_file
- name: Create Machine Config file for Masters
  template:
    src: chrony.conf.j2 
    dest: "{{ config_dest }}/99_master-machine-config-chrony.yaml"
- name: Create Machine Config file for Workers
  template:
    src: chrony.conf.j2 
    dest: "{{ config_dest }}/99_worker-machine-config-chrony.yaml"
- name: Create Master MC template
  command: /usr/local/bin/oc create -f {{ config_dest }}/99_master-machine-config-chrony.yaml --kubeconfig {{ var_config_path }}
- name: Create Worker MC template
  command: /usr/local/bin/oc create -f {{ config_dest }}/99_worker-machine-config-chrony.yaml --kubeconfig {{ var_config_path }}
    



  
